version: '3.8'

services:
  web:
    build: ..
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker

  celery_worker:
    build: ..
    command: celery -A interactive_chart_project worker --loglevel=info
    volumes:
      - ../src:/code
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
